[versions]
agp = "8.10.0"
kotlin = "2.0.21"
androidx-core = "1.16.0"
androidx-appcompat = "1.7.1"
androidx-lifecycle = "2.9.1"
androidx-activity = "1.7.2"
androidx-work = "2.10.2"
okhttp = "4.11.0"
rxjava2 = "2.2.21"
rxandroid = "2.1.1"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version = "androidx-activity" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
rxjava2 = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava2" }
rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxandroid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

